#include "include/game.h"
#include <libdl/math3d.h>


const float TARGET_MIN_SPAWN_DISTANCE[TRAINING_TYPE_MAX] = {
  [TRAINING_TYPE_FUSION] 50,
  [TRAINING_TYPE_B6] 50,
  [TRAINING_TYPE_CYCLE] 10
};

const float TARGET_IDEAL_SPAWN_DISTANCE[TRAINING_TYPE_MAX] = {
  [TRAINING_TYPE_FUSION] 50,
  [TRAINING_TYPE_B6] 50,
  [TRAINING_TYPE_CYCLE] 10
};

const float TARGET_BUFFER_SPAWN_DISTANCE[TRAINING_TYPE_MAX] = {
  [TRAINING_TYPE_FUSION] 50,
  [TRAINING_TYPE_B6] 50,
  [TRAINING_TYPE_CYCLE] 10
};
