#include "include/game.h"
#include <libdl/math3d.h>


const float TARGET_MIN_SPAWN_DISTANCE[TRAINING_TYPE_MAX] = {
  [TRAINING_TYPE_FUSION] 50,
  [TRAINING_TYPE_CYCLE] 10,
  [TRAINING_TYPE_RUSH] 10,
};

const float TARGET_IDEAL_SPAWN_DISTANCE[TRAINING_TYPE_MAX] = {
  [TRAINING_TYPE_FUSION] 50,
  [TRAINING_TYPE_CYCLE] 10,
  [TRAINING_TYPE_RUSH] 50,
};

const float TARGET_BUFFER_SPAWN_DISTANCE[TRAINING_TYPE_MAX] = {
  [TRAINING_TYPE_FUSION] 50,
  [TRAINING_TYPE_CYCLE] 10,
  [TRAINING_TYPE_RUSH] 10,
};

const char * NAMES[] = {
  "cHivAs JoKeR",
  "BooKooKiLLa",
  "Sunny D",
  "Poten-TiaL",
  "//Who Cares",
  "Flag-CapperLag",
  "VeRNoN",
  "..D34DLY..",
  "aAsdf",
  "Star Killer",
  "Flailer*",
  "Red Pirate",
  "Djabsolut121",
  "Hothead2005",
  "thepimp",
  "Thorax",
  "Undeadghost",
  "CANADIAN--KID",
  "_GuNNeR_",
  "InfiniteDragon",
  "-RePubLiC-",
  "HopesandFears",
  "BliND FalCoN",
  "GdOgS4122",
  ":--:iCe:--:",
  "-mexico-",
  "f!r3*",
  "Silent Kid:']",
  "Sapphire Medal",
  "=):::::::::::>",
  "}{ole of death",
  "}{alf Glitch",
  "sTaLe FisH",
  "-Xz Death zX-",
  "u s a #1",
  "FatBlack",
  "Quabbi",
  "Wemsrox",
  "PrO StAtUs",
  "GoT MiLK? O_o",
  "Canada Ftw",
  "-EnsLaveD-",
  "cArMeL-GirL",
  "-FreaKaZoiD-",
  "Major Nuke",
  "-:ZeRo:-",
  "dRuiD",
  "K.O",
  "rawr.<3",
  "FrOsT pRiNcEsS",
  "DeviN982",
  "`dUaLiTy`",
  "Lucci",
  "-French-",
  "ArmbaR",
  "ThePac",
  "Texasboy",
  "iNtent To harM",
  "- XsV -",
  "-Advanced-",
  "reDFlag",
  "Certain Death",
  "Army-Gunz",
  "Tek No",
  "BLAH!!!!!!",
  ".nEw YoRk.",
  "[_-BoT-LeG-_]",
  "Omega3",
  "Mr.Snowman7",
  "My1lastfate",
  "riT",
  "Man in a suit",
  "DGK",
  "Mr.$un$hIn3",
  "EviL DoN",
  "-xTc-",
  "KreeD",
  "Kiku-ichimonji",
  "-eXo-",
  "KyLe1234",
  "-shortii-",
  "BAD GAS",
  "Nonkeyboii",
  "-ShoTGuNsTyLe-",
  "FLuFFy PiLLoW",
  "G.i. Reaper",
  ")-(itMaN",
  "iNmaTe",
  "First Place",
  "Sasori",
  "Q.w.e.r.t.y",
  "VoLcoM.",
  "Boj",
  "Shadowchamp",
  "Flying Tomato",
  "KillaseasoN",
  "*wast3d*",
  "Ryno Mikey",
  "-J1D M4N-",
  "Snow dogg",
  "`cLouD STriFe`",
  "Dr_Pick ^_^",
  "DeatHwisH.",
  "~iPod~",
  "Reliable",
  "cardboard box",
  "speKs",
  "DarkMatter",
  "A red ratchet",
  "-=) KeVMaN (=-",
  "The Pest",
  "-Supremacy-",
  "DEWEYNATOR777",
  "sKePtiCaL",
  "Avenged Sol",
  "R@tC|-|et",
  "Dopey",
  "aCe Boii",
  "Vix",
  "F-116 Charger",
  "CtOwNbAlLa",
  "`Ihab`",
  "ThePhoneGuy",
  "THE BUDDHA",
  "NiPPoLoPoLiS",
  "100%EVIL",
  "Turtlesoup",
  "Super One",
  "CyborgMonkey",
  "Pineapple",
  "JerichoCross13",
  "Monkeyboii",
  "LiVe Or DiE",
  "Me&^C1^nk",
  "Rubyrayquaza",
  "Cheese boy45",
  "RRrd",
  "Alflex",
  "Tidus gang",
  "-cZaR-",
  "-Oprah winfrey",
  "- ReDempTioN -",
  "Zi'Tah-Girl",
  "HOMINID",
  "COfuSDpOptART",
  "bLk",
  "Meta-Ratchet",
  "dLas",
  "Prancing Fairy",
  "UnKnOwNSoLdieR",
  "(Heartless)",
  "DARKJOSH",
  "Pik",
  "Doberainian777",
  "*-KiNgMiCkEy-*",
  "SR004",
  "BrASs MoNkEy",
  "-eNeMy-",
  "Cuznpedro",
  "25 To LiFe",
  "*NumB*",
  "HiT Sn!PeR",
  "BaSeBaLLeR",
  "Takas",
  "^Iron Man^",
  "Crusader boy",
  "ZERO'S GHOST",
  "HVAC_MaN",
  "Hard Style",
  "^-_DeathKiD_-^",
  "-sporky-",
  "FatMattMan",
  "ExPerT SniPeR",
  "tHe_PuNisHeR",
  "C.m.K.",
  "`CrAzYsHoT`",
  "Sm&Ke",
  "BARCODE",
  "Champonraw",
  "'BrOkEn HeArT'",
  "octavarium",
  "REDDEVILS992",
  "Fendertele",
  "IPATH HIPPIE",
  "vegard",
  "Lotond",
  "SuPaMaN",
  "~PaWnAGe~",
  "The Piggy",
  "KiTa",
  "dishank",
  "Jaken.",
  ">>>SuNkIsT<<<",
  "-LiL FurY-",
  "IIIIIIIIIIIIIII",
  "Rambo96",
  "FAt ALbeRT",
  "Tuberculosis"
};

const int NAMES_COUNT = sizeof(NAMES) / sizeof(char*);
