#ifndef _SURVIVAL_VALIX_H_
#define _SURVIVAL_VALIX_H_

#define MAP_BASE_COMPLEXITY         (5000)

// ordered from least to most probable
// never more than MAX_MOB_SPAWN_PARAMS total spawn params
enum MobSpawnParamIds {
  MOB_SPAWN_PARAM_KING_LEVIATHAN,
  MOB_SPAWN_PARAM_LEVIATHAN_COMMON,
  MOB_SPAWN_PARAM_LEVIATHAN,
  MOB_SPAWN_PARAM_REAPER,
  MOB_SPAWN_PARAM_TREMOR,
  MOB_SPAWN_PARAM_NORMAL,
  MOB_SPAWN_PARAM_SWARMER,
  MOB_SPAWN_PARAM_COUNT
};

enum GambitIds {
  GAMBIT_ID_NONE = 0,
  GAMBIT_ID_EASY_MODE,
  GAMBIT_ID_IMPOSSIBLE_MODE,
  GAMBIT_ID_JUMP_PADS_ALWAYS_ACTIVE,
  GAMBIT_ID_RANDOMIZE_JUMP_PADS,
  GAMBIT_ID_HOVERBOOTS,
  GAMBIT_ID_ARBITER_ONLY,
  GAMBIT_ID_MAGMA_CANNON_ONLY,
  GAMBIT_ID_MINES_ONLY,
};

void gambitsOnRoundComplete(int roundNo);
void gambitsTick(void);
void gambitsInit(void);

#endif // _SURVIVAL_VALIX_H_
