#ifndef SURVIVAL_MOB_EXECUTIONER_H
#define SURVIVAL_MOB_EXECUTIONER_H

#define EXECUTIONER_BASE_REACTION_TICKS						  (0.25 * TPS)
#define EXECUTIONER_BASE_ATTACK_COOLDOWN_TICKS			(5 * TPS)
#define EXECUTIONER_BASE_EXPLODE_RADIUS						  (5)
#define EXECUTIONER_MELEE_HIT_RADIUS								(1.75)
#define EXECUTIONER_EXPLODE_HIT_RADIUS							(5)
#define EXECUTIONER_MELEE_ATTACK_RADIUS						  (5)
#define EXECUTIONER_TOO_CLOSE_TO_TARGET_RADIUS		  (8)

#define EXECUTIONER_TARGET_KEEP_CURRENT_FACTOR      (10)

#define EXECUTIONER_MAX_WALKABLE_SLOPE              (40 * MATH_DEG2RAD)
#define EXECUTIONER_BASE_STEP_HEIGHT								(2)
#define EXECUTIONER_TURN_RADIANS_PER_SEC            (45 * MATH_DEG2RAD)
#define EXECUTIONER_TURN_AIR_RADIANS_PER_SEC        (15 * MATH_DEG2RAD)
#define EXECUTIONER_MOVE_ACCELERATION               (25)
#define EXECUTIONER_MOVE_AIR_ACCELERATION           (5)

#define EXECUTIONER_ANIM_ATTACK_TICKS							  (30)
#define EXECUTIONER_TIMEBOMB_TICKS									(60 * 2)
#define EXECUTIONER_FLINCH_COOLDOWN_TICKS					  (60 * 7)
#define EXECUTIONER_ACTION_COOLDOWN_TICKS					  (30)
#define EXECUTIONER_RESPAWN_AFTER_TICKS						  (60 * 30)
#define EXECUTIONER_BASE_COLL_RADIUS								(0.5)
#define EXECUTIONER_MAX_COLL_RADIUS								  (4)
#define EXECUTIONER_AMBSND_MIN_COOLDOWN_TICKS    	  (60 * 2)
#define EXECUTIONER_AMBSND_MAX_COOLDOWN_TICKS    	  (60 * 3)
#define EXECUTIONER_FLINCH_PROBABILITY             (0.05)

#endif // SURVIVAL_MOB_EXECUTIONER_H
