#ifndef SURVIVAL_MOB_REACTOR_H
#define SURVIVAL_MOB_REACTOR_H

#define REACTOR_BASE_REACTION_TICKS						  (0.25 * TPS)
#define REACTOR_BASE_ATTACK_COOLDOWN_TICKS			(3 * TPS)
#define REACTOR_BASE_EXPLODE_RADIUS						  (5)
#define REACTOR_MELEE_HIT_RADIUS								(1.75)
#define REACTOR_EXPLODE_HIT_RADIUS							(5)
#define REACTOR_MELEE_ATTACK_RADIUS						  (5)

#define REACTOR_MAX_DIST_FOR_CHARGE		          (30)
#define REACTOR_CHARGE_ATTACK_MIN_COOLDOWN_TICKS    (TPS * 10)
#define REACTOR_CHARGE_ATTACK_MAX_COOLDOWN_TICKS    (TPS * 30)
#define REACTOR_CHARGE_ATTACK_MIN_STALL_LOOPS   (1)
#define REACTOR_CHARGE_ATTACK_MAX_STALL_LOOPS   (4)
#define REACTOR_CHARGE_SPEED                    (50)
#define REACTOR_CHARGE_ACCELERATION             (60)
#define REACTOR_CHARGE_MAX_SLOPE                (45 * MATH_DEG2RAD)

#define REACTOR_SHOT_WITH_TRAIL_MAX_DIST        (50)
#define REACTOR_SHOT_WITH_TRAIL_ATTACK_MIN_COOLDOWN_TICKS     (TPS * 20)
#define REACTOR_SHOT_WITH_TRAIL_ATTACK_MAX_COOLDOWN_TICKS     (TPS * 40)
#define REACTOR_SHOT_WITH_TRAIL_TURN_RADIANS_PER_SEC      (45 * MATH_DEG2RAD)
#define REACTOR_SHOT_WITH_TRAIL_SHOT_SPEED                (30 * MATH_DT)

#define REACTOR_TARGET_KEEP_CURRENT_FACTOR      (10)

#define REACTOR_MAX_WALKABLE_SLOPE              (40 * MATH_DEG2RAD)
#define REACTOR_BASE_STEP_HEIGHT								(2)
#define REACTOR_TURN_RADIANS_PER_SEC            (45 * MATH_DEG2RAD)
#define REACTOR_TURN_AIR_RADIANS_PER_SEC        (15 * MATH_DEG2RAD)
#define REACTOR_MOVE_ACCELERATION               (25)
#define REACTOR_MOVE_AIR_ACCELERATION           (5)

#define REACTOR_ANIM_ATTACK_TICKS							  (30)
#define REACTOR_TIMEBOMB_TICKS									(60 * 2)
#define REACTOR_FLINCH_COOLDOWN_TICKS					  (60 * 7)
#define REACTOR_ACTION_COOLDOWN_TICKS					  (30)
#define REACTOR_RESPAWN_AFTER_TICKS						  (60 * 30)
#define REACTOR_BASE_COLL_RADIUS								(1.5)
#define REACTOR_MAX_COLL_RADIUS								  (4)
#define REACTOR_AMBSND_MIN_COOLDOWN_TICKS    	  (60 * 2)
#define REACTOR_AMBSND_MAX_COOLDOWN_TICKS    	  (60 * 3)
#define REACTOR_FLINCH_PROBABILITY              (0.05)

enum ReactorAnimId
{
	REACTOR_ANIM_IDLE,
	REACTOR_ANIM_STEP_BACK_KNEE_DOWN,
	REACTOR_ANIM_KNEE_DOWN,
	REACTOR_ANIM_KNEE_DOWN_STEP_UP,
	REACTOR_ANIM_TAUNT_GRAB,
	REACTOR_ANIM_TAUNT_BICEP_FLEX,
	REACTOR_ANIM_LOOK_DOWN_LEFT_RIGHT,
	REACTOR_ANIM_SHIMMY_LEFT,
	REACTOR_ANIM_SHIMMY_RIGHT,
	REACTOR_ANIM_WOBBLE_LEFT,
	REACTOR_ANIM_WOBBLE_RIGHT,
	REACTOR_ANIM_JUMP_UP,
	REACTOR_ANIM_FIRE_FROM_PALM_LEFT,
	REACTOR_ANIM_FIRING_FROM_PALM_LEFT,
	REACTOR_ANIM_FIRING_FROM_PALM_LEFT_RECOIL,
	REACTOR_ANIM_FIRE_FROM_PALM_LEFT_EXIT,
	REACTOR_ANIM_TAUNT_HANDS_UP_FOR_CROWD,
	REACTOR_ANIM_FLINCH_BEND_OVER,
	REACTOR_ANIM_PREPPING_TWO_HAND_PULSE,
	REACTOR_ANIM_FIRE_TWO_HAND_PULSE,
	REACTOR_ANIM_THROW_GRENADE,
	REACTOR_ANIM_RUN,
	REACTOR_ANIM_WALK_QUICKLY_BACKWARD,
	REACTOR_ANIM_WALK_SLOWLY_FORWARD,
	REACTOR_ANIM_SQUAT_PREPARE_FOR_DASH,
	REACTOR_ANIM_SQUAT_PREPARE_FOR_DASH_FOOT_RUB_GROUND,
	REACTOR_ANIM_SQUAT_PREPARE_FOR_DASH_FOOT_RUB_GROUND2,
	REACTOR_ANIM_RUN_QUICKLY_FORWARD,
	REACTOR_ANIM_SPRINT_SWING,
	REACTOR_ANIM_JUMP_SMASH,
	REACTOR_ANIM_FLINCH_SMALL,
	REACTOR_ANIM_FLINCH_FLY_BACK,
	REACTOR_ANIM_FLINCH_FALL_DOWN,
	REACTOR_ANIM_DIE,
	REACTOR_ANIM_SWING,
	REACTOR_ANIM_ENTER_FLY_MODE,
	REACTOR_ANIM_FLY_MODE,
	REACTOR_ANIM_EXIT_FLY_MODE,
};

enum ReactorBangles {
	REACTOR_BANGLE_SHOULDER_PLATES =  	  (1 << 0),
};

enum ReactorAction
{
	REACTOR_ACTION_SPAWN,
	REACTOR_ACTION_IDLE,
	REACTOR_ACTION_JUMP,
	REACTOR_ACTION_WALK,
	REACTOR_ACTION_FLINCH,
	REACTOR_ACTION_BIG_FLINCH,
	REACTOR_ACTION_LOOK_AT_TARGET,
  REACTOR_ACTION_DIE,
	REACTOR_ACTION_ATTACK_SWING,
	REACTOR_ACTION_ATTACK_CHARGE,
	REACTOR_ACTION_ATTACK_SHOT_WITH_TRAIL,
};

enum ReactorSubskeletonJoints
{
  REACTOR_SUBSKELETON_JOINT_CHEST = 0,
  REACTOR_SUBSKELETON_JOINT_NECK = 1,
  REACTOR_SUBSKELETON_JOINT_HIPS = 2,
  REACTOR_SUBSKELETON_JOINT_LEFT_HAND = 3,
  REACTOR_SUBSKELETON_JOINT_RIGHT_HAND = 4,
};

typedef struct ReactorMobVars
{
  Moby* PrepShotWithFireParticleMoby1;
  Moby* PrepShotWithFireParticleMoby2;
  float AnimSpeedAdditive;
  char ChargeChargeupTargetCount;
  char HasFiredTrailshotThisLoop;
} ReactorMobVars_t;

#endif // SURVIVAL_MOB_REACTOR_H
