#ifndef SURVIVAL_MOB_REAPER_H
#define SURVIVAL_MOB_REAPER_H

#define REAPER_BASE_REACTION_TICKS						(0.25 * TPS)
#define REAPER_BASE_ATTACK_COOLDOWN_TICKS			(2 * TPS)
#define REAPER_BASE_EXPLODE_RADIUS						(5)
#define REAPER_MELEE_HIT_RADIUS								(1.75)
#define REAPER_EXPLODE_HIT_RADIUS							(5)
#define REAPER_MELEE_ATTACK_RADIUS						(5)

#define REAPER_TARGET_KEEP_CURRENT_FACTOR     (10.0)

#define REAPER_MAX_WALKABLE_SLOPE             (40 * MATH_DEG2RAD)
#define REAPER_BASE_STEP_HEIGHT								(2)
#define REAPER_TURN_RADIANS_PER_SEC           (45 * MATH_DEG2RAD)
#define REAPER_TURN_AIR_RADIANS_PER_SEC       (15 * MATH_DEG2RAD)
#define REAPER_MOVE_ACCELERATION              (25)
#define REAPER_MOVE_AIR_ACCELERATION          (5)

#define REAPER_ANIM_ATTACK_TICKS							(30)
#define REAPER_TIMEBOMB_TICKS									(60 * 2)
#define REAPER_FLINCH_COOLDOWN_TICKS					(60 * 7)
#define REAPER_ACTION_COOLDOWN_TICKS					(30)
#define REAPER_RESPAWN_AFTER_TICKS						(60 * 30)
#define REAPER_BASE_COLL_RADIUS								(0.5)
#define REAPER_MAX_COLL_RADIUS								(4)
#define REAPER_AMBSND_MIN_COOLDOWN_TICKS    	(60 * 2)
#define REAPER_AMBSND_MAX_COOLDOWN_TICKS    	(60 * 3)
#define REAPER_FLINCH_PROBABILITY             (1.0)

enum ReaperAnimId
{
	REAPER_ANIM_UNDERGROUND,
	REAPER_ANIM_IDLE,
	REAPER_ANIM_2,
	REAPER_ANIM_WALK,
	REAPER_ANIM_AGGRO_WALK,
	REAPER_ANIM_RUN,
	REAPER_ANIM_JUMP,
	REAPER_ANIM_CROUCH,
	REAPER_ANIM_ELECTROCUTED,
	REAPER_ANIM_CRAWL_OUT_OF_GROUND,
	REAPER_ANIM_FLINCH,
	REAPER_ANIM_THROW_HEAD,
	REAPER_ANIM_TAUNT,
	REAPER_ANIM_CAT_PASS,
	REAPER_ANIM_BIG_FLINCH,
	REAPER_ANIM_SLAP,
	REAPER_ANIM_IDLE_2
};

enum ReaperBangles {
	REAPER_BANGLE_HEAD_1 =  	(1 << 0),
	REAPER_BANGLE_HEAD_2 =  	(1 << 1),
	REAPER_BANGLE_HEAD_3 =  	(1 << 2),
	REAPER_BANGLE_HEAD_4 =  	(1 << 3),
	REAPER_BANGLE_HEAD_5 =  	(1 << 4),
	REAPER_BANGLE_TORSO_1 = 	(1 << 5),
	REAPER_BANGLE_TORSO_2 = 	(1 << 6),
	REAPER_BANGLE_TORSO_3 = 	(1 << 7),
	REAPER_BANGLE_TORSO_4 = 	(1 << 8),
	REAPER_BANGLE_HIPS = 			(1 << 9),
	REAPER_BANGLE_LLEG = 			(1 << 10),
	REAPER_BANGLE_RFOOT = 		(1 << 11),
	REAPER_BANGLE_RLEG = 			(1 << 12),
	REAPER_BANGLE_RARM = 			(1 << 13),
	REAPER_BANGLE_LARM = 			(1 << 14),
	REAPER_BANGLE_HIDE_BODY =	(1 << 15)
};

enum ReaperAction
{
	REAPER_ACTION_SPAWN,
	REAPER_ACTION_IDLE,
	REAPER_ACTION_JUMP,
	REAPER_ACTION_WALK,
	REAPER_ACTION_FLINCH,
	REAPER_ACTION_BIG_FLINCH,
	REAPER_ACTION_LOOK_AT_TARGET,
  REAPER_ACTION_DIE,
	REAPER_ACTION_ATTACK,
	REAPER_ACTION_TIME_BOMB,
  REAPER_ACTION_TIME_BOMB_EXPLODE
};

#endif // SURVIVAL_MOB_REAPER_H
