#ifndef SURVIVAL_MOB_ZOMBIE_H
#define SURVIVAL_MOB_ZOMBIE_H

#define ZOMBIE_BASE_REACTION_TICKS						(0.25 * TPS)
#define ZOMBIE_BASE_ATTACK_COOLDOWN_TICKS			(2 * TPS)
#define ZOMBIE_BASE_EXPLODE_RADIUS						(5)
#define ZOMBIE_MELEE_HIT_RADIUS								(1.75)
#define ZOMBIE_EXPLODE_HIT_RADIUS							(5)
#define ZOMBIE_MELEE_ATTACK_RADIUS						(5)

#define ZOMBIE_TARGET_KEEP_CURRENT_FACTOR     (10)

#define ZOMBIE_MAX_WALKABLE_SLOPE             (40 * MATH_DEG2RAD)
#define ZOMBIE_BASE_STEP_HEIGHT								(2)
#define ZOMBIE_TURN_RADIANS_PER_SEC           (45 * MATH_DEG2RAD)
#define ZOMBIE_TURN_AIR_RADIANS_PER_SEC       (15 * MATH_DEG2RAD)
#define ZOMBIE_MOVE_ACCELERATION              (25)
#define ZOMBIE_MOVE_AIR_ACCELERATION          (5)

#define ZOMBIE_ANIM_ATTACK_TICKS							(30)
#define ZOMBIE_TIMEBOMB_TICKS									(60 * 2)
#define ZOMBIE_FLINCH_COOLDOWN_TICKS					(60 * 7)
#define ZOMBIE_ACTION_COOLDOWN_TICKS					(30)
#define ZOMBIE_RESPAWN_AFTER_TICKS						(60 * 30)
#define ZOMBIE_BASE_COLL_RADIUS								(0.5)
#define ZOMBIE_MAX_COLL_RADIUS								(4)
#define ZOMBIE_AMBSND_MIN_COOLDOWN_TICKS    	(60 * 2)
#define ZOMBIE_AMBSND_MAX_COOLDOWN_TICKS    	(60 * 3)
#define ZOMBIE_FLINCH_PROBABILITY             (0.05)

#endif // SURVIVAL_MOB_ZOMBIE_H
